### ISSUE TITLE
why

### ISSUE THREAD

**Issue by olliem5** [gav06/EventAPI#2]
i will fix this when i get home

**Comment by gav06** [comment]
whats wrong with it?

**Comment by olliem5** [comment]
if you want, i can make it a dependency that you add to your gradle buildscript 
also, why did you get rid of event state and event priority lmao

**Comment by gav06** [comment]
because i never use those lol

**Comment by gav06** [comment]
i just wanted something super lightweight
and only had the most essential stuff

**Comment by jaydevelopsshit** [comment]
Lmfao
